### ISSUE TITLE
Unnecessary provides function for DetailRepository

### ISSUE THREAD

**Issue by ashwindmk** [skydoves/Pokedex#32]
This is not an issue, just a query/suggestion.

https://github.com/skydoves/Pokedex/blob/fa471475a09ba99cf58000cbbe6230186d160568/app/src/main/java/com/skydoves/pokedex/di/RepositoryModule.kt#L45

Since you are already using `@Inject` in the `DetailRepository`, why do you need the `provideDetailRepository` function?

**Comment by skydoves** [comment]
Hi, 
As you said we can build without the `RepositoryModule` because the `@Inject` annotation is attached to repositories.
But this is a demonstration project to show how to construct the di environment, like `ViewModelComponent` and `ViewModelScoped`. So I added the `RepositoryModule` for showing DI graphs explicitly.

**Comment by ashwindmk** [comment]
> Hi,
> As you said we can build without the `RepositoryModule` because the `@Inject` annotation is attached to repositories.
> But this is a demonstration project to show how to construct the di environment, like `ViewModelComponent` and `ViewModelScoped`.
> So I added the `RepositoryModule` for showing DI graphs explicitly.
> 
> Thanks!

Got it, thanks for the explanation.
